language: android
android:
  components:
    - build-tools-20.0.0
    - android-20
  script:
      - echo "Travis branch is $TRAVIS_BRANCH"
      - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
      - gradle build